[tools]
node = "20"

[tasks."api.dev"]
env = { PYTHONIOENCODING = "utf-8", PYTHONUTF8 = "1" }
run = "poetry run fastapi dev app/main.py"

[tasks.setup]
depends = ["setup.back", "setup.front"]

[tasks."api.front"]
dir = "frontend"
run = "npm run dev"

[tasks."setup.back"]
run = """
poetry install
poetry run alembic upgrade head
"""

[tasks."setup.front"]
dir = "frontend"
run = "npm install"

[tasks."front.lint"]
dir = "frontend"
run = "npm run lint"

[tasks."back.lint"]
dir = "app"
run = "poetry run ruff check"

[tasks."back.lint.fix"]
dir = "app"
run = "poetry run ruff check --fix"

[tasks."back.formatter"]
description = "Run Ruff formatter on the app/ directory"
dir="app"
run = "poetry run ruff format ."

[tasks."back.test"]
dir = "app"
run = "poetry run pytest"

[tasks."front.test"]
dir = "frontend"
run = "npm run test"

[tasks."back.e2e.setup"]
env = { DATABASE_URL = "sqlite:///{{ config_root }}/gamelog_test.db" }
run = [
  "poetry run python -c \"import os; os.remove('gamelog_test.db') if os.path.exists('gamelog_test.db') else None\"",
  "poetry run alembic upgrade head"
]

[tasks."e2e.test"]
dir = "frontend"
depends = ["back.e2e.setup"]
env = { PLAYWRIGHT_BROWSERS_PATH = "0", DATABASE_URL = "sqlite:///{{ config_root }}/gamelog_test.db" }
run = "npm run test:e2e"

[tasks."e2e.ui"]
dir = "frontend"
depends = ["back.e2e.setup"]
env = { PLAYWRIGHT_BROWSERS_PATH = "0", DATABASE_URL = "sqlite:///{{ config_root }}/gamelog_test.db" }
run = "npm run test:e2e:ui"