"""Refactoring and optimizing backend VisualMemory

Revision ID: 1451640390bf
Revises: ccf09b148d4e
Create Date: 2026-07-17 13:54:47.848840

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1451640390bf'
down_revision: Union[str, Sequence[str], None] = 'ccf09b148d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


import json

def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    
    # Tabela temporária para ler/escrever os dados
    games_table = sa.Table(
        'games',
        sa.MetaData(),
        sa.Column('id', sa.String()),
        sa.Column('platforms', sa.String()),
        sa.Column('genres', sa.String())
    )
    
    # Busca e limpa os dados antes de fazer o ALTER
    results = conn.execute(sa.select(games_table.c.id, games_table.c.platforms, games_table.c.genres)).fetchall()
    for row in results:
        game_id, platforms, genres = row
        
        new_platforms = platforms
        new_genres = genres
        changed = False
        
        if platforms and isinstance(platforms, str):
            if platforms.startswith("["):
                new_platforms = platforms.replace("'", '"')
            else:
                new_platforms = json.dumps([platforms])
            changed = True
            
        if genres and isinstance(genres, str):
            if genres.startswith("["):
                new_genres = genres.replace("'", '"')
            else:
                new_genres = json.dumps([genres])
            changed = True
            
        if changed:
            conn.execute(
                games_table.update().where(games_table.c.id == game_id).values(
                    platforms=new_platforms,
                    genres=new_genres
                )
            )

    # Agora sim podemos alterar as colunas sabendo que todo o dado é JSON válido (stringificada)
    if conn.dialect.name == 'postgresql':
        with op.batch_alter_table('games', schema=None) as batch_op:
            batch_op.alter_column('platforms',
                   existing_type=sa.VARCHAR(),
                   type_=sa.JSON(),
                   existing_nullable=True,
                   postgresql_using='platforms::json')
            batch_op.alter_column('genres',
                   existing_type=sa.VARCHAR(),
                   type_=sa.JSON(),
                   existing_nullable=True,
                   postgresql_using='genres::json')
    else:
        with op.batch_alter_table('games', schema=None) as batch_op:
            batch_op.alter_column('platforms',
                   existing_type=sa.VARCHAR(),
                   type_=sa.JSON(),
                   existing_nullable=True)
            batch_op.alter_column('genres',
                   existing_type=sa.VARCHAR(),
                   type_=sa.JSON(),
                   existing_nullable=True)

    with op.batch_alter_table('tier_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tier_items_game_id'), ['game_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tier_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tier_items_game_id'))

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('genres',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('platforms',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
