"""Refactoring and optimizing backend VisualMemory

Revision ID: 1451640390bf
Revises: ccf09b148d4e
Create Date: 2026-07-17 13:54:47.848840

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1451640390bf'
down_revision: Union[str, Sequence[str], None] = 'ccf09b148d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('platforms',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='platforms::json')
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='genres::json')

    with op.batch_alter_table('tier_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tier_items_game_id'), ['game_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tier_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tier_items_game_id'))

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('genres',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('platforms',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
