"""Add user_game_reviews table

Revision ID: 4c98e5afe83d
Revises: 4475cdaa4893
Create Date: 2026-07-21 17:20:32.803164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c98e5afe83d'
down_revision: Union[str, Sequence[str], None] = '4475cdaa4893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_game_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_game_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_game_id'], ['user_games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_game_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_game_reviews_user_game_id'), ['user_game_id'], unique=False)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('game_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('user_game_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_game_reviews_user_game_id'))

    op.drop_table('user_game_reviews')
    # ### end Alembic commands ###
