"""add_tierlist_privacy_and_flexible_activities

Revision ID: 6550828fd3bc
Revises: 4c98e5afe83d
Create Date: 2026-07-26 14:36:01.773186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6550828fd3bc'
down_revision: Union[str, Sequence[str], None] = '4c98e5afe83d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_user_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tierlist_id', sa.String(), nullable=True))
        batch_op.alter_column('game_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_activities_target_user_id'), ['target_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_tierlist_id'), ['tierlist_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_activities_target_user_id_users'), 'users', ['target_user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_activities_tierlist_id_tierlists'), 'tierlists', ['tierlist_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tierlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.text('true')))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tierlists', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_activities_tierlist_id_tierlists'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_activities_target_user_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_activities_tierlist_id'))
        batch_op.drop_index(batch_op.f('ix_activities_target_user_id'))
        batch_op.alter_column('game_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('tierlist_id')
        batch_op.drop_column('target_user_id')

    # ### end Alembic commands ###
