"""add_soft_delete_and_created_at

Revision ID: 785ac4603bb2
Revises: 5188f4537cb9
Create Date: 2026-07-02 13:23:56.387691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785ac4603bb2'
down_revision: Union[str, Sequence[str], None] = '5188f4537cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    else:
        op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
