"""add_gog_accounts_table

Revision ID: 8cb04cfc93c9
Revises: 6550828fd3bc
Create Date: 2026-08-13 22:30:51.173201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb04cfc93c9'
down_revision: Union[str, Sequence[str], None] = '6550828fd3bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gog_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('persona_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_gog_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gog_accounts'))
    )
    with op.batch_alter_table('gog_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gog_accounts_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gog_accounts_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gog_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gog_accounts_username'))
        batch_op.drop_index(batch_op.f('ix_gog_accounts_user_id'))

    op.drop_table('gog_accounts')
    # ### end Alembic commands ###
