"""Add itch_accounts table

Revision ID: a20e025de8dc
Revises: 1451640390bf
Create Date: 2026-07-17 15:07:18.626895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a20e025de8dc'
down_revision: Union[str, Sequence[str], None] = '1451640390bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itch_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('itch_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itch_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itch_accounts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itch_accounts_itch_id'), ['itch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itch_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itch_accounts_itch_id'))
        batch_op.drop_index(batch_op.f('ix_itch_accounts_id'))

    op.drop_table('itch_accounts')
    # ### end Alembic commands ###
