"""Add new fields to usergame

Revision ID: ba4bcb8a7491
Revises: 
Create Date: 2026-06-26 11:53:15.782720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4bcb8a7491'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('custom_lists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('platforms', sa.String(), nullable=True),
    sa.Column('genres', sa.String(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_external_id'), 'games', ['external_id'], unique=True)
    op.create_table('tierlists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_list_games',
    sa.Column('custom_list_id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['custom_list_id'], ['custom_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('custom_list_id', 'game_id')
    )
    op.create_table('tier_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tierlist_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tierlist_id'], ['tierlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_games',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('finished_at', sa.Date(), nullable=True),
    sa.Column('acquired_at', sa.Date(), nullable=True),
    sa.Column('platinum_at', sa.Date(), nullable=True),
    sa.Column('hours_played', sa.Float(), nullable=True),
    sa.Column('store', sa.Enum('STEAM', 'EPIC', 'GOG', 'ITCH', 'PS_STORE', 'XBOX', 'NINTENDO', 'GOOGLE_PLAY', 'APP_STORE', 'PHYSICAL', 'OTHER', name='store'), nullable=True),
    sa.Column('custom_cover_url', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tier_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['tier_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tier_items')
    op.drop_table('user_games')
    op.drop_table('tier_categories')
    op.drop_table('custom_list_games')
    op.drop_table('tierlists')
    op.drop_index(op.f('ix_games_external_id'), table_name='games')
    op.drop_table('games')
    op.drop_table('custom_lists')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
