"""add_steam_integration

Revision ID: cc435a414017
Revises: 785ac4603bb2
Create Date: 2026-07-02 20:40:59.459944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc435a414017'
down_revision: Union[str, Sequence[str], None] = '785ac4603bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steam_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('steam_id', sa.String(), nullable=False),
    sa.Column('persona_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('games', sa.Column('steam_appid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_games_steam_appid'), 'games', ['steam_appid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_steam_appid'), table_name='games')
    op.drop_column('games', 'steam_appid')
    op.drop_table('steam_accounts')
    # ### end Alembic commands ###
