"""add release_year platforms genres to game

Revision ID: fd4b5af55b4f
Revises: 2d16f40d52ee
Create Date: 2026-06-22 22:45:09.201502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd4b5af55b4f'
down_revision: Union[str, Sequence[str], None] = '2d16f40d52ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('release_year', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('platforms', sa.String(), nullable=True))
    op.add_column('games', sa.Column('genres', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'genres')
    op.drop_column('games', 'platforms')
    op.drop_column('games', 'release_year')
    # ### end Alembic commands ###
