/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PatchNotesRouteImport } from './routes/patch-notes'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as SocialRouteImport } from './routes/social'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as TierlistsIndexRouteImport } from './routes/tierlists.index'
import { Route as TierlistsIdRouteImport } from './routes/tierlists.$id'
import { Route as SettingsIntegrationsItchCallbackRouteImport } from './routes/settings.integrations.itch.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatchNotesRoute = PatchNotesRouteImport.update({
  id: '/patch-notes',
  path: '/patch-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const TierlistsIndexRoute = TierlistsIndexRouteImport.update({
  id: '/tierlists/',
  path: '/tierlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const TierlistsIdRoute = TierlistsIdRouteImport.update({
  id: '/tierlists/$id',
  path: '/tierlists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntegrationsItchCallbackRoute =
  SettingsIntegrationsItchCallbackRouteImport.update({
    id: '/settings/integrations/itch/callback',
    path: '/settings/integrations/itch/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/patch-notes': typeof PatchNotesRoute
  '/recommendations': typeof RecommendationsRoute
  '/social': typeof SocialRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/tierlists/$id': typeof TierlistsIdRoute
  '/profile/': typeof ProfileIndexRoute
  '/tierlists/': typeof TierlistsIndexRoute
  '/settings/integrations/itch/callback': typeof SettingsIntegrationsItchCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/patch-notes': typeof PatchNotesRoute
  '/recommendations': typeof RecommendationsRoute
  '/social': typeof SocialRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/tierlists/$id': typeof TierlistsIdRoute
  '/profile': typeof ProfileIndexRoute
  '/tierlists': typeof TierlistsIndexRoute
  '/settings/integrations/itch/callback': typeof SettingsIntegrationsItchCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/patch-notes': typeof PatchNotesRoute
  '/recommendations': typeof RecommendationsRoute
  '/social': typeof SocialRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/tierlists/$id': typeof TierlistsIdRoute
  '/profile/': typeof ProfileIndexRoute
  '/tierlists/': typeof TierlistsIndexRoute
  '/settings/integrations/itch/callback': typeof SettingsIntegrationsItchCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/library'
    | '/login'
    | '/patch-notes'
    | '/recommendations'
    | '/social'
    | '/profile/$userId'
    | '/tierlists/$id'
    | '/profile/'
    | '/tierlists/'
    | '/settings/integrations/itch/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/library'
    | '/login'
    | '/patch-notes'
    | '/recommendations'
    | '/social'
    | '/profile/$userId'
    | '/tierlists/$id'
    | '/profile'
    | '/tierlists'
    | '/settings/integrations/itch/callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/library'
    | '/login'
    | '/patch-notes'
    | '/recommendations'
    | '/social'
    | '/profile/$userId'
    | '/tierlists/$id'
    | '/profile/'
    | '/tierlists/'
    | '/settings/integrations/itch/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  PatchNotesRoute: typeof PatchNotesRoute
  RecommendationsRoute: typeof RecommendationsRoute
  SocialRoute: typeof SocialRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  TierlistsIdRoute: typeof TierlistsIdRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  TierlistsIndexRoute: typeof TierlistsIndexRoute
  SettingsIntegrationsItchCallbackRoute: typeof SettingsIntegrationsItchCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patch-notes': {
      id: '/patch-notes'
      path: '/patch-notes'
      fullPath: '/patch-notes'
      preLoaderRoute: typeof PatchNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tierlists/': {
      id: '/tierlists/'
      path: '/tierlists'
      fullPath: '/tierlists/'
      preLoaderRoute: typeof TierlistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tierlists/$id': {
      id: '/tierlists/$id'
      path: '/tierlists/$id'
      fullPath: '/tierlists/$id'
      preLoaderRoute: typeof TierlistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/integrations/itch/callback': {
      id: '/settings/integrations/itch/callback'
      path: '/settings/integrations/itch/callback'
      fullPath: '/settings/integrations/itch/callback'
      preLoaderRoute: typeof SettingsIntegrationsItchCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  PatchNotesRoute: PatchNotesRoute,
  RecommendationsRoute: RecommendationsRoute,
  SocialRoute: SocialRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  TierlistsIdRoute: TierlistsIdRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  TierlistsIndexRoute: TierlistsIndexRoute,
  SettingsIntegrationsItchCallbackRoute: SettingsIntegrationsItchCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
